select top 1 * from catalogue_data
select top 1 * from rating_data
select top 1 * from consumption_data
select top 1 * from subscription_data

--Which is the most watched movie? 

select top 1 title , sum(user_duration) as watch_time from catalogue_data as c 
inner join consumption_data x
on c.content_id = x.content_id
group by title
order by watch_time desc

--Which movies has not been watched at all?

select top 1 title , sum(user_duration) as watch_time from catalogue_data as c 
inner join consumption_data x
on c.content_id = x.content_id
group by title
order by watch_time 

--Calculate the % of total revenue generated by the different plan types

select plan_type , (sum(amount_paid) / ( select sum(amount_paid) from subscription_data))*100
as [revenue%]
from subscription_data
where plan_type is not null
group by plan_type

--Which movies are helping us aquire most number of users?

create procedure top_rating_movies @n int
as
select top (@n) title , count(feedback_id) as ratings 
from catalogue_data as c
inner join consumption_data as x
on c.content_id = x.content_id
inner join rating_data as r
on r.userid = x.userid and r.usersessionid = x.usersessionid
where r.rating = 'AWESOME'
group by title
order by count(feedback_id) desc

exec top_rating_movies @n = 50

--All content which has been live for last 6 months

select title
from catalogue_data
where status = 'LIVE'
       and
	   date_added > (select DATEADD(month , -6 ,max(date_added)) from catalogue_data)
